---

- name: Restart egress-auditor
  ansible.builtin.systemd:
    name: egress-auditor
    state: restarted
    daemon_reload: true

- name: Reload egress-auditor nftables rules
  ansible.builtin.command:
    cmd: nft -f /etc/nftables.d/custom/egress-auditor.nft
  changed_when: false
